#!/usr/bin/env python3
"""Varredura de falsos positivos — Google Places apenas."""
import json, re
from collections import Counter

with open('data/terreiros_all_sources.json') as f:
    data = json.load(f)
records = data['terreiros']

# Count by source
source_counts = Counter(r.get('fonte','') for r in records)
print("=== REGISTROS POR FONTE ===")
for s, c in source_counts.most_common():
    print(f"  {s:12s}: {c}")
print()

google_records = [r for r in records if r.get('fonte') == 'google']
non_google = [r for r in records if r.get('fonte') != 'google']
print(f"Google: {len(google_records)} | Nao-Google: {len(non_google)}")
print()

# Afro-Brazilian religious keywords (Yoruba, Bantu, Jeje, Umbanda, general)
religious_terms = [
    # Yoruba/Ketu
    'candombl', 'terreiro', 'tereiro', 'ile', 'ilê', 'axé', 'asé', 'ase', 'axe',
    'orixá', 'orixa', 'orisa', 'orisha', 'egun', 'egungun', 'orun',
    'oxum', 'iemanjá', 'iemanja', 'yemanja', 'yemanjá', 'iansã', 'iansa', 'yansa',
    'nanã', 'nana', 'oxóssi', 'oxossi', 'ogun', 'ogum', 'xangô', 'xango', 'sango',
    'exu', 'esu', 'eshu', 'ossaim', 'logun', 'oxumarê', 'oxumare', 'omulu',
    'obaluaye', 'oxalá', 'oxala', 'orunmila', 'ifá', 'ifa',
    'alaketu', 'alabaxê', 'bimódé', 'bimode', 'akueran', 'omiparan',
    'aramefá', 'aramefa', 'alaketu', 'alafin', 'sidenã',
    # Bantu/Angola/Congo
    'inzo', 'inzó', 'unzo', 'unzó', 'onzo', 'onzó', 'nzo', 'nzó',
    'mansu', 'manso', 'mansú', 'nkisi', 'inkisi', 'inkice', 'nkice',
    'dandalunda', 'dandalun', 'danda', 'matamba', 'zunga',
    'kaiango', 'kaiongo', 'mutalombo', 'mutalambo', 'gongombira', 'gongobila',
    'gongá', 'gonga', 'junsara', 'junçara', 'junssara', 'junge', 'jinge',
    'tumbenci', 'tombenci', 'tumba', 'tumb',
    'kavungo', 'kavun', 'kawani', 'mpaanzu',
    'lemba', 'lembafuranga', 'lembên', 'lembeuaji', 'lemim', 'lemb',
    'kassanji', 'kasanji', 'kondiogongo', 'katendê', 'katend', 'kondi',
    'kuenku', 'inkinomsabu', 'inkinansaba',
    'mametu', 'mameto', 'mamet', 'kaiongo',
    'nkisi', 'nkice', 'ganzua', 'ganzu', 'ganz',
    'sasaganzu', 'bamburucema', 'bamburuce',
    'kiatalala', 'kiasampalak', 'kiameian', 'kameian',
    'nzambi', 'zambi', 'zambe', 'uzambe', 'unzambe', 'inzambe',
    'amaz', 'amazi', 'amaze', 'amean', 'ameán', 'mean',
    'kaiaia', 'mavula', 'mungongo',
    'mutazingu', 'mutalabo', 'sambango',
    'unkuanxi', 'umuene', 'nongongo', 'vasambilua',
    'kupavi', 'tovivo', 'bosu', 'besen', 'vodun', 'vodum',
    'abassá', 'abassa', 'abass', 'kafum', 'kafung', 'kafunge',
    'kissimi', 'tata', 'dizami', 'tateto', 'tatet', 'tatatu',
    # Umbanda
    'tenda', 'gira', 'caboclo', 'preto velho', 'pomba gira', 'pombagira',
    'boiadeiro', 'baiano', 'baianinha', 'cigan', 'cigano', 'malandro',
    'pajé', 'paje', 'jurema', 'catimbó', 'catimbo', 'mesa branca',
    'encruzilhada', 'assentamento', 'quimbanda', 'macumba', 'umbanda',
    'umbandist', 'aruanda', 'aluanda',
    # Jeje/Fon
    'vodun', 'vodum', 'aje', 'bosu', 'besen', 'kupavi', 'tovivo',
    'hevioso', 'sogbo', 'sogb', 'nana buluku', 'buruku',
    # General
    'casa de santo', 'casa de mina', 'batuque', 'batucada', 'roça', 'roca',
    'abaça', 'abaca', 'barco', 'zoogod', 'mae de santo', 'pai de santo',
    'mãe de santo', 'pai de santo', 'mae pequena', 'pai pequeno',
    'senzala', 'templo umbandist', 'vale do amanhecer',
    'casa de caridade', 'centro espirit', 'fraternidade umbandist',
    'ogando', 'ogamor', 'ogun deui', 'ogum deui', 'ogun ara', 'ogun beira',
    # additional terms seen in data
    'odé', 'odê', 'obá', 'oyá', 'oya', 'lewá', 'lewa', 'dewá', 'dewa', 'dew',
    'omim', 'onipó', 'onipo', 'kongo', 'congo', 'angola', 'bessy', 'gimboleci',
    'ewew', 'tintun', 'guere betan', 'guerreiro de gong', 'funanji',
    'inxaourou', 'itubenssara', 'lembaroci', 'luã dew', 'luã', 'miro',
    'ofá', 'mucumbi', 'nkice', 'leusi', 'luanza', 'ngunzo',
    'mukkunn', 'senzala religiosa', 'cavaleiros de aruanda',
    'templo ogun', 'ogum', 'ogun', 'terreio', 'tualandê', 'tualande',
    'nigunci', 'dinicosi', 'tenda nanã', 'sake', 'ungambi', 'seman',
    'giro de boiadeiro', 'centro de boiadeiro', 'giro eru', 'giro jubiabá',
    'centro de giro', 'centro de yemanjá', 'sete flechas',
    'cosme', 'dami', 'dandalunda', 'oiyá', 'oiya', 'olorun', 'diunzamb',
    'pena branca', 'rei de macambira', 'sessão de giro', 'sessao de giro',
    'shoramin', 'nilê', 'nile', 'jakurika', 'atim', 'uzambe',
    'kaingango', 'kapango', 'kakurakaia', 'kanzua', 'inkonsi', 'danbeleuci',
    'kanzuá', 'monaleuci', 'kae adamoxi', 'oraibó', 'oraib', 'megí', 'megi',
    'kunzó', 'kunzo', 'tateto', 'kimongo', 'pongo', 'nuelo',
    'lembá', 'danda lungua', 'concuazenza', 'ungurucemavulu',
    'mansubandu', 'mansun bandun', 'maramatamba', 'mikero', 'mutuiçara',
    'atombessi', 'ninge lemim', 'guere', 'gume sogboadan', 'filho de azacrá',
    'ingongo de zamb', 'gimboleci', 'lembaroci',
    'mutalombo yê kaiongo', 'mutalambo y sambango',
    'tombensi neto', 'lemba junssara', 'meso', 'wanz', 'junsara',
    'kwa kayongo', 'unkuanxi', 'vasambilua',
    'mukkunndewá', 'mukkunndewa', 'fraternidade umbandist',
    'cavaleiros de aruanda', 'aluanda', 'aruanda',
    'tenda espirit', 'centro espirit', 'templo umbandist',
    'casa de caridade', 'vale do amanhecer', 'templo ogun',
    'ogando', 'ogamor', 'ogum deui', 'ogun deui',
    'odé mirim', 'odé oni fará', 'odé oni', 'odê oni', 'odé taomi', 'odé kelesi',
    'obá tony', 'obá kanfé', 'obá carilê', 'obá dêmin', 'obá airá', 'obá oxê lodê',
    'oyá madé', 'oyá dey', 'oyá funké', 'oyá vanjú', 'oyá matamba', 'oyá lunda',
    'oyá sidã', 'oyá', 'dandalunda cantumbereci', 'dandalunda oya',
    'dandalunda de unzambe', 'oiyá kassarongongo', 'gente de guiné',
    'olorum ioyá', 'omim deayá', 'omim lewá', 'diunzambí', 'pena branca',
    'rei de macambira', 'sake de lozenza', 'seman de ungambi', 'sessão de giro',
    'sessao de giro', 'shoramin nilê', 'suitala mean', 'sultão das matas',
    'jakurika atim', 'uzambe', 'jinge junçara', 'kongo',
    'kaingango kapango', 'kakurakaia', 'kanzua inkonsi', 'danbeleuci',
    'kanzuá monaleuci', 'kae adamoxi oraibó megí', 'kafungê',
    'kissimiã tata dizami', 'kunzó tateto kimongo pongo nuelo',
    'lembá dilê', 'danda lungua', 'concuazenza', 'ungurucemavulu',
    'mansubandu kuenkue', 'mansun bandun kuêkuê', 'maramatamba',
    'mikero', 'mutuiçara', 'neto do atombessi', 'ninge lemim',
    'guere betan gume sogboadan', 'filho de azacrá', 'funanji filho',
    'gimboleci', 'ingongo de zamb', 'inxaourou', 'itubenssara',
    'lembaroci', 'luã dewá', 'miro',
    'mutalombo yê kaiongo', 'mutalambo y sambango',
    'ofá mucumbi deomazi', 'nkice', 'mutazinguê', 'tombenci neto',
    'sasaganzuá katitembu', 'kiatalala', 'mba katuala',
    'kanjoãnlojolo', 'kangunga', 'kiasampalakãnuá',
    'bamburucema talê', 'danda mutaleci', 'lemba junssara',
    'leusi', 'luanza', 'mavula', 'matamba', 'meso', 'wanz', 'junsara',
    'ngunzo kwa kayongo', 'unkuanxi', 'vasambilua',
    'senzala religiosa mukkunndewá', 'fraternidade umbandist cavaleiros',
    'cavaleiros de aruanda', 'aluanda', 'aruanda',
    # Additional from the ambiguous list
    'asipa', 'aziani', 'ayá banají', 'azé iatemi', 'babá bokiní', 'babá odé',
    'ajonsor', 'fanfun ké', 'gêge dahomé', 'ijá obe ocutá', 'jobe omim',
    'milaia', 'nancy omim', 'oiá gibericó', 'oiá odi koroadê', 'omam omim tundê',
    'omi oro', 'omo ketá', 'omô oconlá', 'passadãn', 'onomi', 'ore-ofê', 'oreofê',
    'tomim kiosise', 'três unidos', 'yalode', 'oni ofélélé', 'carilê',
    'ojisé amonilê', 'agbaj', 'lembê aluanda', 'bakisé', 'sasa ganzu',
    'gongará kaiango', 'humuraxá', 'indembwa', 'kamumzambi', 'tumba jun',
    'amaze', 'amazi', 'kessimbe', 'catulande', 'gunzelê', 'kuna zambi',
    'kassanji', 'katendê', 'kondiogongo', 'inkisi', 'tombensi', 'malaula',
    'kunã lembên', 'lembafuranga', 'lonboji', 'maiamba', 'malawlakuna',
    'bate folinha', 'mona di ameán', 'nkinongo', 'lucaia', 'sidirá tucá',
    'yeye yeye mim', 'vintém de prata', 'viva deus', 'bisneto', 'indelê',
    'vodun zó', 'yeieu omim', 'ladê', 'yiá teí', 'ylê', 'ylê alé',
    'ylê arco verde', 'ylê legi odé', 'ylê asse omim', 'becendã', 'celombó',
    'agelú', 'ynssu gunzu', 'kilombata', 'ogum deui', 'talo', 'kegan',
    'd.ioyá', 'kewanvolá', 'tira teima', 'suitala mean', 'sultão das matas',
    'sunfucia', 'talakise', 'tanurí', 'tata maquende', 'terreio adê',
    'tualandê nigunci', 'dinicosi', 'tenda nanã', 'sake de lozenza',
    'ungambi', 'seman de ungambi', 'sessão de giro', 'shoramin nilê',
    'danda lewa', 'dandalunda', 'oiyá', 'olorum', 'diunzamb',
    'tumba jussara', 'tumba jussara', 'tumba',
    'gimbol', 'gimbol',
    'centro de boiadeiro', 'centro de giro eru', 'centro de giro jubiabá',
    'centro de yemanjá', 'centro do cabolco', 'centro do caboclo',
    'sete flechas', 'com deus', 'cosme e dami',
    # Bantu religious structures
    'onzo', 'onzo congo', 'onzo mean', 'onzo de tingóngo',
    'onzó mutalambo', 'onzó tata dyungunzo', 'onzo nguzo',
    'unzó', 'unzo', 'unzo amazi', 'unzo catulande', 'unzo gunzelê',
    'unzo kassanji', 'unzo katendê', 'unzo kondiogongo',
    'unzo kuna inkisi', 'unzo kunã', 'unzo lembafuranga',
    'unzo lonboji', 'unzo maiamba', 'unzo malawlakuna',
    'unzo mona di ameán', 'unzo nkinongo lucaia',
    'unzo oya', 'unzo roxe mucumbi', 'unzo sasaganzuá',
    'unzo sidirá', 'unzo yeye', 'unzó', 'unzó amaze',
    'unzó catulande', 'unzó gunzelê', 'unzó kassanji',
    'unzó katendé', 'unzó kondiogongo', 'unzó kuna',
    'unzó kunã', 'unzó lembafuranga', 'unzó lonboji',
    'unzó maiamba', 'unzó malawlakuna', 'unzó mona',
    'unzó nkinongo', 'unzó oya', 'unzó roxe', 'unzó sasaganzuá',
    'unzó sidirá', 'unzó yeye',
    'onzo congo bessy', 'onzo congo mutalombó', 'onzo mean avulô',
    'onzo nguzo za nkisi', 'onzo de tingóngo',
    # More Yoruba
    'ilê', 'ilê asè', 'ilê axé', 'ilê ase', 'ilè', 'ilè asè',
    'ilè àse', 'ilé', 'ilé àse', 'ilé ase',
    'ilê asipa', 'ilê axè', 'ilê azé', 'ilê ayá', 'ilê babá',
    'ilê de', 'ilê fanfun', 'ilê gedemerê', 'ilê gêge',
    'ilê ijá', 'ilê jobe', 'ilê milaia', 'ilê nancy',
    'ilê obá', 'ilê odô', 'ilê oiá', 'ilê omam', 'ilê omi',
    'ilê omo', 'ilê onomi', 'ilê ore', 'ilê tomim',
    'ilê três', 'ilê yá', 'ilê àse', 'ilê ôba', 'ilê ôni',
    'ilê asè', 'ilê asé', 'ilê asé', 'ilê asé',
    'ibugbé', 'ibá faron', 'ibá oji',
    'ilè asè iàló', 'ilè àse ewé', 'ilé àse ejó',
    'ilê ajé', 'ilê alainakô', 'ilê ashé', 'ilê asipa',
    'ilê axè', 'ilê ayá', 'ilê azé', 'ilê babá', 'ilê de',
    'ilê fanfun', 'ilê gedemerê', 'ilê gêge', 'ilê ijá',
    'ilê jobe', 'ilê milaia', 'ilê nancy', 'ilê obá',
    'ilê odô', 'ilê oiá', 'ilê omam', 'ilê omi', 'ilê omo',
    'ilê onomi', 'ilê ore', 'ilê tomim', 'ilê três',
    'ilê yá', 'ilê àse', 'ilê ôba', 'ilê ôni',
    # More from SEFAZ
    'daome', 'mburasi', 'iba faromim', 'ide ode kelesi',
    'omo alade', 'onzo gonzo', 'onzo kaiajamba', 'onzo meam',
    'onzo muta eusi', 'onzo zambe', 'oya omim bale',
    'oluaie', 'oju aiye', 'lecy omi', 'oni okutã', 'lewa',
    'manso bantu', 'manso gongombira', 'manso sinavurù',
    'mansu gongobila', 'mansu kaiango', 'mansu tateetu',
    'marlom', 'risalva', 'herminia', 'anuciacao',
    'rumpayme', 'dan', 'senzala religiosa',
    'templo umbandista', 'casa de caridade',
    'tanuri junsara', 'tumba junsara', 'tumbenci',
    'uati', 'unzo dandamutale', 'unzo de mameto',
    'unzo de mutalambo', 'unzo dilongatala', 'unzo dyazule',
    'unzo gandoia', 'unzo kavungo', 'unzo kawani',
    'unzo kwa mpaanzu', 'unzo lemba', 'unzo leusi',
    'unzo maiala', 'unzo maianba', 'unzo manambe',
    'unzo mean ria kaiaia', 'unzo mutalabo', 'unzo ngunzo',
    'unzo onimboya', 'unzo ofá', 'unzó de nkice',
    'unzó mutalombô', 'unzó sasaganzuá', 'unzó bamburucema',
    'uzo unkuanxi', 'vodun kwe', 'tumbe',
    # additional from CEAO
    'caboclo serra', 'centro de caboclo', 'gira de caboclo',
    'centro do caboclo', 'centro de caboclo eru',
    'centro de caboclo serra', 'gira de caboclo de serra',
    'caboclo', 'centro de boiadeiro', 'centro de giro',
    'centro de yemanjá', 'com deus', 'cosme e dami',
    'danda lewa', 'dandalunda', 'dandalunda cantumbereci',
    'dandalunda oya', 'dandalunda de unzambe', 'dewá',
    'dialunda', 'd.ioyá kegan', 'euhangue', 'filho de azacrá',
    'funanji filho', 'gimboleci', 'gimboleci',
    'guere betan', 'guerreiro de gongá', 'ibugbé',
    'ingongo de zambê', 'inxaourou', 'itubenssara',
    'jakurika atim', 'jinge junçara', 'kafungê',
    'kaiango kapango', 'kakurakaia', 'kanzua inkonsi',
    'kanzuá monaleuci', 'kae adamoxi', 'kissimiã',
    'kunzó tateto', 'lembá dilê', 'lembê aluanda',
    'lembaroci', 'luã dewá', 'luã dew', 'miro',
    'mutalombo yê', 'mutalambo y', 'ofá mucumbi',
    'omim lewá', 'omim deayá', 'onzo congo',
    'onzo mean', 'onzo de tingóngo', 'oyá madé',
    'oyá dey', 'pena branca', 'rei de macambira',
    'sake de lozenza', 'seman de ungambi', 'sessão de giro',
    'shoramin nilê', 'suitala mean', 'sultão das matas',
    'sunfucia', 'talakise', 'tanurí', 'tanurí junçara',
    'tata maquende', 'terreio adê', 'tualandê nigunci',
    'tumba jussara', 'tumba', 'vodun zó', 'yeieu omim',
    'yiá teí', 'ylê alé', 'ylê arco verde', 'ylê legi',
    'ylê asse', 'ynssu gunzu', 'ogum deui',
    'dandalunda', 'oyá', 'odé', 'obá', 'omim', 'lewá',
    'dewá', 'onipó', 'kongo', 'angola', 'bessy',
    'gimbol', 'ewew', 'tintun', 'guere', 'funanji',
    'inxaourou', 'itubenssara', 'lembaroci', 'luã',
    'miro', 'ofá', 'nkice', 'leusi', 'luanza',
    'mavula', 'matamba', 'meso', 'wanz', 'junsara',
    'ngunzo', 'unkuanxi', 'vasambilua',
    'senzala', 'fraternidade', 'cavaleiros',
    'aluanda', 'aruanda', 'tenda espirit', 'centro espirit',
    'templo umbandist', 'casa de caridade',
    'vale do amanhecer', 'templo ogun', 'ogando', 'ogamor',
    'ogum deui', 'ogun deui',
    'tenda umbandist', 'tenda espiritualista',
    'centro espiritualista', 'centro espírita',
    'casa de oxalá', 'casa de santo',
    'abassá', 'abassa', 'casa de mina',
    'zoogod', 'batuque', 'roça', 'roca', 'abaça', 'abaca',
    'barco', 'candomblé', 'candomble',
    'ile asé', 'ilê asé', 'ilê axé', 'ilê ase',
    'mae de santo', 'pai de santo', 'mãe de santo',
    'mae pequena', 'pai pequeno', 'mãe pequena',
    'asé', 'axé', 'axe', 'ase',
    'orixá', 'orixa', 'orisa', 'egun',
    'vodun', 'vodum', 'vodoun',
    'nkisi', 'inkisi', 'nkice', 'inkice',
    'inzo', 'unzo', 'onzo', 'nzo', 'inzó', 'unzó', 'onzó', 'nzó',
    'mansu', 'manso', 'mansú',
    'dandalunda', 'matamba', 'kaiango', 'kaiongo',
    'mutalombo', 'mutalambo', 'gongombira', 'gongobila',
    'junsara', 'junçara', 'junssara',
    'tumbenci', 'tombenci', 'tumba',
    'lemba', 'lembafuranga',
    'kassanji', 'kondiogongo', 'katendê',
    'mametu', 'mameto',
    'ganzua', 'sasaganzu',
    'bamburucema', 'bamburuce',
    'nzambi', 'zambi', 'zambe', 'uzambe', 'unzambe', 'inzambe',
    'amaz', 'amazi', 'amaze', 'amean',
    'kavungo', 'kawani', 'mpaanzu',
    'unkuanxi', 'umuene', 'vasambilua',
    'kupavi', 'tovivo', 'bosu', 'besen',
    'abassá', 'abassa', 'kafum', 'kafung', 'kafunge',
    'kissimi', 'tata', 'tateto',
    'caboclo', 'preto velho', 'pomba gira', 'pombagira',
    'boiadeiro', 'baiano', 'cigan', 'malandro',
    'pajé', 'paje', 'jurema', 'catimbó', 'catimbo',
    'encruzilhada', 'assentamento', 'quimbanda', 'macumba',
    'umbanda', 'umbandist',
    'tenda', 'gira', 'centro espirit', 'centro espírita',
    'tenda espirit', 'tenda espiritualista',
    'centro espiritualista',
    'casa de caridade', 'vale do amanhecer',
    'templo ogun', 'ogando', 'ogamor',
    'senzala', 'fraternidade umbandist',
    'cavaleiros de aruanda', 'aluanda', 'aruanda',
    # short but religious
    'oyá', 'odé', 'obá', 'omim', 'lewá', 'dewá',
    'onipó', 'kongo', 'angola', 'bessy', 'gimbol',
    'ewew', 'tintun', 'guere', 'funanji', 'inxaourou',
    'itubenssara', 'lembaroci', 'luã', 'miro',
    'ofá', 'nkice', 'leusi', 'luanza', 'mavula',
    'matamba', 'meso', 'wanz', 'junsara', 'ngunzo',
    'unkuanxi', 'vasambilua', 'senzala', 'fraternidade',
    'cavaleiros', 'aluanda', 'aruanda',
    'dandalun', 'danda', 'tumba', 'lemba', 'kassanji',
    'kondi', 'katend', 'mamet', 'ganzu', 'ganz',
    'bamburuc', 'nzambi', 'zambi', 'zambe', 'uzambe',
    'unzambe', 'inzambe', 'amaz', 'amazi', 'amaze',
    'amean', 'kavungo', 'kawani', 'mpaanzu',
    'unkuanxi', 'umuene', 'vasambilua',
    'kupavi', 'tovivo', 'bosu', 'besen',
    'abass', 'kafum', 'kafung', 'kafunge',
    'kissimi', 'tateto',
    'caboclo', 'boiadeiro', 'baiano', 'cigan',
    'malandro', 'pajé', 'paje', 'jurema',
    'catimbó', 'catimbo', 'quimbanda', 'macumba',
    'umband', 'tenda', 'gira',
    'ogum', 'ogun', 'oxum', 'iemanjá', 'iemanja',
    'xangô', 'xango', 'exu', 'esu', 'oxóssi', 'oxossi',
    'oxalá', 'oxala', 'omulu', 'oxumarê', 'oxumare',
    'ossaim', 'logun', 'nanã', 'nana', 'iansã', 'iansa',
    'orixá', 'orixa', 'orisa', 'egun',
    'vodun', 'vodum', 'candomblé', 'candomble',
    'terreiro', 'tereiro', 'roça', 'roca', 'abaça', 'abaca',
    'batuque', 'zoogod', 'casa de santo', 'casa de mina',
    'mae de santo', 'pai de santo', 'mãe de santo',
    'axé', 'asé', 'axe', 'ase',
    'ile', 'ilê', 'ilè', 'ilé',
    'nkisi', 'inkisi', 'nkice', 'inkice',
    'inzo', 'unzo', 'onzo', 'nzo',
    'mansu', 'manso',
    'dandalunda', 'matamba', 'kaiango',
    'mutalombo', 'mutalambo', 'gongombira',
    'junsara', 'junçara', 'tumbenci',
    'lemba', 'kassanji', 'kondiogongo',
    'mametu', 'mameto', 'ganzua',
    'bamburucema', 'nzambi', 'zambi',
    'amaz', 'amazi', 'kavungo', 'kawani',
    'kupavi', 'bosu', 'besen',
    'abass', 'kafung', 'kafunge',
    'kissimi', 'tateto',
    'caboclo', 'preto velho', 'pomba gira',
    'boiadeiro', 'baiano', 'cigan', 'malandro',
    'pajé', 'jurema', 'catimbó',
    'quimbanda', 'macumba', 'umbanda',
    'tenda', 'gira', 'centro espirit',
    'casa de caridade', 'vale do amanhecer',
    'senzala', 'fraternidade', 'cavaleiros',
    'aluanda', 'aruanda',
    'ogando', 'ogamor',
    # Critical: these are religious terms even though they look like common words
    'onzo', 'onzo congo', 'onzo mean', 'onzo muta',
    'unzo', 'unzo amazi', 'unzo catulande',
    'unzo gunzelê', 'unzo kassanji', 'unzo katendê',
    'unzo kondiogongo', 'unzo kuna', 'unzo kunã',
    'unzo lembafuranga', 'unzo lonboji', 'unzo maiamba',
    'unzo malawlakuna', 'unzo mona', 'unzo nkinongo',
    'unzo oya', 'unzo roxe', 'unzo sasaganzuá',
    'unzo sidirá', 'unzo yeye',
    'unzó', 'unzó amaze', 'unzó catulande',
    'unzó gunzelê', 'unzó kassanji', 'unzó katendé',
    'unzó kondiogongo', 'unzó kuna', 'unzó kunã',
    'unzó lembafuranga', 'unzó lonboji', 'unzó maiamba',
    'unzó malawlakuna', 'unzó mona', 'unzó nkinongo',
    'unzó oya', 'unzó roxe', 'unzó sasaganzuá',
    'unzó sidirá', 'unzó yeye',
    'nzó', 'nzó amaze',
    # more
    'ingongo', 'inxaourou', 'itubenssara',
    'lembaroci', 'luã', 'miro', 'ofá', 'nkice',
    'leusi', 'luanza', 'mavula', 'matamba',
    'meso', 'wanz', 'junsara', 'ngunzo',
    'unkuanxi', 'vasambilua',
    'senzala', 'fraternidade', 'cavaleiros',
    'aluanda', 'aruanda',
    'tenda espirit', 'centro espirit',
    'centro espiritualista', 'centro espírita',
    'templo umbandist', 'casa de caridade',
    'vale do amanhecer', 'templo ogun',
    'ogando', 'ogamor', 'ogum deui', 'ogun deui',
    'dewá', 'dew', 'lewá', 'lew', 'omim',
    'onipó', 'onipo', 'kongo', 'angola',
    'bessy', 'gimbol', 'gimboleci',
    'ewew', 'tintun', 'guere', 'funanji',
    'inxaourou', 'itubenssara', 'lembaroci',
    'luã', 'miro', 'ofá', 'nkice',
    'leusi', 'luanza', 'mavula', 'matamba',
    'meso', 'wanz', 'junsara', 'ngunzo',
    'unkuanxi', 'vasambilua',
    'tenda', 'gira', 'caboclo', 'boiadeiro',
    'baiano', 'cigan', 'malandro',
    'pajé', 'jurema', 'catimbó',
    'quimbanda', 'macumba', 'umbanda',
    'centro espirit', 'casa de caridade',
    'vale do amanhecer', 'senzala',
    'fraternidade', 'cavaleiros',
    'aluanda', 'aruanda',
    'ogando', 'ogamor', 'ogum deui',
    'dandalun', 'danda', 'tumba',
    'lemba', 'kassanji', 'kondi',
    'katend', 'mamet', 'ganzu', 'ganz',
    'bamburuc', 'nzambi', 'zambi', 'zambe',
    'uzambe', 'unzambe', 'inzambe',
    'amaz', 'amazi', 'amaze', 'amean',
    'kavungo', 'kawani', 'mpaanzu',
    'kupavi', 'tovivo', 'bosu', 'besen',
    'abass', 'kafum', 'kafung', 'kafunge',
    'kissimi', 'tateto',
    'oyá', 'odé', 'obá', 'omim', 'lewá',
    'dewá', 'onipó', 'kongo', 'angola',
    'bessy', 'gimbol', 'ewew', 'tintun',
    'guere', 'funanji', 'inxaourou',
    'itubenssara', 'lembaroci', 'luã',
    'miro', 'ofá', 'nkice', 'leusi',
    'luanza', 'mavula', 'matamba',
    'meso', 'wanz', 'junsara', 'ngunzo',
    'unkuanxi', 'vasambilua', 'senzala',
    'fraternidade', 'cavaleiros', 'aluanda',
    'aruanda', 'tenda', 'gira', 'caboclo',
    'boiadeiro', 'baiano', 'cigan', 'malandro',
    'pajé', 'jurema', 'catimbó', 'quimbanda',
    'macumba', 'umbanda', 'centro espirit',
    'casa de caridade', 'vale do amanhecer',
    'senzala', 'fraternidade', 'cavaleiros',
    'aluanda', 'aruanda', 'ogando', 'ogamor',
    'ogum deui', 'dandalun', 'danda', 'tumba',
    'lemba', 'kassanji', 'kondi', 'katend',
    'mamet', 'ganzu', 'ganz', 'bamburuc',
    'nzambi', 'zambi', 'zambe', 'uzambe',
    'unzambe', 'inzambe', 'amaz', 'amazi',
    'amaze', 'amean', 'kavungo', 'kawani',
    'mpaanzu', 'kupavi', 'tovivo', 'bosu',
    'besen', 'abass', 'kafum', 'kafung',
    'kafunge', 'kissimi', 'tateto',
]

# Build a set for fast lookup (lowercased)
religious_set = set()
for term in religious_terms:
    religious_set.add(term.lower().strip())

def has_religious_keyword(nome_lower):
    """Check if any religious term appears as a substring."""
    for term in religious_set:
        if term in nome_lower:
            return True
    return False

# Non-religious patterns for Google entries
non_religious_patterns = [
    ('Hotel/pousada', r'hotel|pousada|hostel|albergue'),
    ('Pet shop', r'pet\s*shop|mascote\s*pet'),
    ('Bar/restaurante', r'restaurante|bar\b|lanchonet|cafeteria|quiosque|delivery|meat\s*house|choperia|petiscaria|pastel|sabor\s*da\s*casa|tempero\s*da\s*ilha|queijos|frios|casa\s*do\s*tempero|casa\s*de\s*frios|casa\s*do\s*queijo|la\s*casa\s*de\s*pastel|quintal\s*de\s*casa'),
    ('Material construcao', r'material\s*de\s*constru|madeireira|telhas|casa\s*de\s*constru|casa\s*&\s*constru|casa\s*das\s*telhas'),
    ('Saude/instituicao', r'hospital|clini|posto\s*de\s*saude|consultor|estetica|oftalm|prefeit|prefecture|santa\s*casa'),
    ('Loja', r'enxov|moda|boutique|fashion|acabamentos|kasabella'),
    ('Mercado', r'supermerc|mercearia|convenien|mercad|varej|atacad|mercadinho'),
    ('Estacionamento', r'estacion'),
    ('Salao', r'barbeari|cabelele'),
    ('Academia', r'academia|crossfit|muscula'),
    ('Imobiliaria', r'agencia|imobil|locac|aluguel|corretor|avaliador|imobiliar'),
    ('Servicos', r'informatica|audio\s*tec|junior\s*som|som\s*em\s*ilheus|vini\s*audio'),
    ('Shopping/infra', r'shopping|airport|aeroporto|parque\s*shopping'),
    ('Rede lojas', r'casas?\s*bahia|casas?\s*baiana'),
    ('Rural', r'fazenda|sitio\s*(arqueolog|historico|raio|santo\s*antonio|do\s*quinto|santana)|chacara'),
    ('Igreja catolica/evangelica', r'igreja\s*(universal|catolica|nova|do\s*divino)|universal\s*church|paroquia|parish|cathedral|diocese|basilica|congregacao|igreja\s*catolica|san\s*sebastian|san\s*francisco\s*church|st\.?\s*ant|nossa\s*senhora|sao\s*thomaz|sao\s*domingos|capela\s*da\s*serra|capela\s*de\s*santo|igreja\s*nova|ruinas\s*da\s*igreja|diocesan|casa\s*paroquial|centro\s*de\s*espiritualidade\s*santa|diocese'),
    ('Infra/transporte', r'marina|lighthouse|farol|terminal|rodoviaria|safe\s*harbor|vlt|balsa|passarela|terminal\s*(fluvial|maritimo|rodoviario)|porto\s*seco|porto\s*center'),
    ('Cultura/memorial', r'culture\s*center|centro\s*de\s*cultura|palacio\s*das\s*artes|museu|memorial|monument|nucleo\s*historico|ruinas|afro.brazilian\s*museum|cultural\s*afro\s*brazilian'),
    ('Cemiterio', r'cemiterio|campo\s*santo'),
    ('Quilombo nao-terreiro', r'quilombo\s*(ere|zizi|de\s*zeca)'),
    ('Comercio', r'comerc|comercio|distribuid|adega|bazar|lojas?\s*(b\s*moveis|santa\s*barbara|santo\s*andre|verdes\s*mares|santo\s*antonio|reino|central|st|shop\s*st)|padaria|laticinios|loteria|mercadinho|varejao|atacad'),
    ('Acougue', r'casa\s*de\s*carne'),
    ('Loja artigos', r'artesanat|artigos?\s*religios|artigos?\s*african|essencias\s*e\s*ervas|raio\s*do\s*sol\s*artigos|tok\s*ess'),
    ('Fabricante', r'fabricante|fabrica|atelier|atelie|casa\s*9'),
    ('Fundacao', r'fundaca'),
    ('Assistencia social', r'associacao\s*(de\s*maes|batista|baiana\s*de\s*avicultura|de\s*morador|comunit)|abrigo|lar\s*espirita|lar\s*da\s*serenidade|asilo|casa\s*de\s*apoio|casa\s*para\s*idosos|projeto\s*social'),
    ('Espiritismo/Kardecismo', r'espirita|espirit|centro\s*espirita|centro\s*espiritualista|taize\s*community|bethany|secal|sociedade\s*espirita|lar\s*espirita|centro\s*espiritualista\s*(brilho|ceu|divina)'),
    ('Juridico', r'advogad|oab|ordem\s*dos\s*advogados'),
    ('Nao-religioso generico', r'lago|praia\s*de|mirante|serra\s*(do|da|dourada)|morro\s*do\s*(chapeu|chapéu|ouro)|chapada|parque\s*history|beco|praca|alto\s*do\s*cruzeiro|monumento|cidade\s*historica|city\s*of\s*serra|spring\s*island|lagoon|jegue|cachoeira\s*do\s*villa|rial|condominio|loteamento|residencial|ilha\s*(de|di|grande|lesbos|ibiza|capri)|playa|praia\s*em|praia\s*resort|ec\s*resort|resort|all\s*inclusive|trekking|passarela\s*do|maior\s*sanfona|serra\s*do\s*abi|pe\s*de\s*serra|serra\s*da\s*santa\s*cruz|monte\s*de\s*tanquinho|casa\s*do\s*morro|casa\s*pedacinho|cabana|barraca\s*de\s*praia|ax[eé]\s*beach|casa\s*da\s*praia|casa\s*de\s*temporada|villa|casa\s*flor|casa\s*arcadia|casa\s*design|casa\s*verde|casa\s*oliveira|casa\s*mascarenhas|casa\s*vasconcelos|casa\s*tucano|casa\s*valen|casa\s*dez|casa\s*tobias|casa\s*mariano|casa\s*bateia|casa\s*popular|casa\s*nova|casa\s*da\s*pessoa|casa\s*do\s*p[eé]|casa\s*do\s*rio|casa\s*do\s*espanto|casa\s*das\s*resistencias|casa\s*de\s*cec[ií]lia|casa\s*de\s*costura|casa\s*paroquial|nossa\s*casa\s*(church|itacare)|casa\s*de\s*dona'),
    ('Instituicao publica', r'universidade|university|centro\s*universitario|sac\s*municipal|secretaria|prefeitura|rodoviaria|prefecture'),
    ('Industria/servicos', r'agua\s*mineral|absa\s*limpa|fossa|cosmeticos|industria|inpasa|lazo\s*industria|matecol|absa\s*locac|enzo\s*informatica'),
    ('Indigena', r'aldeia\s*(filhos|tupyara|tupinamba|pena\s*verde)|indian|filhos\s*de\s*tupinamba|tupinamba|monument.*indian|monument\s*to\s*indian'),
    ('Comercio espiritual', r'mae\s*de\s*santo.*pai\s*de\s*santo|vidente|tarolog|casa\s*de\s*consulta'),
    ('Maçonaria', r'loja\s*ma[çc]onica|ma[çc]onica'),
    ('Turismo', r'porto\s*seguro\s*praia|porto\s*seguro\s*aeroporto|passarela\s*do\s*descobrimento|orla\s*(de|ii|do)'),
]

# BA municipality names
ba_city_names = {
    'buerarema','joao dourado','joão dourado','tanbacu','tanquinho','tapiramuta',
    'sento se','sento sé','quijingue','uauá','saubara','remanso','muritiba',
    'serra dourada','paratinga','piripá','barro alto','ribeira do pombal',
    'entroncamento','eunapolis','eunápolis','alagoinhas','candeias','ibirapuã',
    'jitauna','jitaúna','juazeiro','valença','valenca','porto seguro','lencois',
    'lençóis','brumado','guanambi','seabra','itabuna','ilheus','ilhéus','camacari',
    'feira de santana','santo amaro','dias d avila','dias davila','araci','araçi',
    'bom jesus da lapa','formosa do rio preto','barreiras','luis eduardo',
    'luís eduardo','sao felix','são félix','conceiçao da feira','conceição da feira',
    'sao francisco','são francisco','amargosa','anagé','anage','belmonte',
    'itambe','itambé','itapitanga','potiragua','potiraguá','itaparica',
    'maragogipe','sao sebastiao','são sebastião','cachoeira','sao felipe',
    'são felipe','governador mangabeira','sapeacu','sapeaçu','tucano','itubera',
    'ituberá','nazare','nazaré','antonio cardoso','antônio cardoso','angical',
    'baianopolis','baianópolis','brejoes','brejões','caravelas','mucuri',
    'teixeira de freitas','medeiros neto','nova vicosa','nova viçosa','itabela',
    'santa cruz cabralia','santa cruz cabrália','itamaraju','prado','alcobaca',
    'alcobaça','trancoso','arraial d ajuda','arraial d\'ajuda','abrantes',
    'ipiau','ipiaú','jequie','jequié','jaguaquara','maracas','maraçás','mutuipe',
    'mutuípe','itirucu','itiruçu','boquira','ibipitanga','macaubas','macaúbas',
    'ibotirama','morpara','morpará','xique xique','xique-xique','buritirama',
    'sao jose','são josé','casa nova','serrinha','santo estevao','santo estêvão',
    'conceiçao do jacuipe','conceição do jacuípe','teodoro sampaio',
    'coraçao de maria','coração de maria','santo antonio de jesus',
    'santo antônio de jesus','irara','irará','satiro dias','sátiro dias',
    'itaberaba','itapicuru','sao desiderio','são deserío','sao jose da vitoria',
    'são josé da vitória','sitio do quinto','sitio do mato','varzea da roca',
    'varzea do poco','varzea do poço','poco halley','poço halley',
    'riachao do jacuipe','riachão do jacuípe','madre de deus','mata de sao joao',
    'mata de são joao','pau brasil','pirai do norte','piraí do norte',
    'santa maria da vitoria','santa maria da vitória','teolandia','teolândia',
    'varzedo','ponto novo','teixeirinha','rosangela','lira','luar',
    'matrix square','casa','agazetabahia','ceak','ceasa','ceasa juazeiro',
    'abapa','fucabase','site iguanambi','terluz','iel eunapolis','iel eunápolis',
    'loja central','kasabella','enzo','pax santos','santos divino','santos de fe',
    'sb dos santos','santos & santos','padaria uniao santos','supermerc santos',
    'laticinios santos','loteria santos','b s santos','agu mineral j santos',
    'marlom','risalva','herminia','rumpayme','tanhaçu','tanquinho bahia',
    'tapiramutá','sento sé','uauá','saubara','remanso ba','muritiba-ba',
    'serra dourada','paratinga sucesso','quijingue','rosangela',
    'lira','luar','matrix square','casa','casa verde','casa nova','casa design',
    'casa oliveira','casa mascarenhas','casa vasconcelos','casa tucano',
    'casa valenca','casa dez','casa tobias','casa mariano','casa bateia',
    'casa popular','agazetabahia','ceak','ceasa','ceasa juazeiro','abapa',
    'fucabase','site iguanambi','terluz','iel eunapolis','loja central',
    'kasabella','enzo','pax santos','santos divino','santos de fe',
    'sb dos santos','santos & santos','padaria uniao santos',
    'supermerc santos','laticinios santos','loteria santos',
    'b s santos','agu mineral j santos','serapião','tanhaçu',
    'tanquinho bahia','tapiramutá','sento sé','uauá','saubara',
    'remanso ba','muritiba-ba','serra dourada','paratinga sucesso',
    'quijingue','rosangela','lira','luar','matrix square','casa',
    'ponto novo bahia','sitio santo antônio','sitio do quinto',
    'sitio do mato','são josé da vitória','são joão de cruz das almas',
    'varzea do poco bahia','vitoria da conquista bahia',
    'xique xique bahia','madre de deus ba','mata de sao joao',
    'pau brasil','piraí do norte','santa maria da vitoria',
    'teolandia','varzedo','barrocas','biritinga','cachoeira',
    'cardeal da silva','conceição do coite','coribe','cotegipe',
    'cravolandia','dario meira','dom basilio','elisio medrado',
    'gaviao','gongogi','ibirataia','ichu','iguaraci',
    'ipecaeta','ipira','iramaia','itaete','itaguacu da bahia',
    'itaju do colonia','itamaru','itaquara','itiruca','ituacu',
    'jacaraci','jaguaripe','jandaira','lajedao','lajedinho',
    'lajedo','lapao','licinio de almeida','livramento',
    'macajuba','maetinga','malhada','malhada de pedras',
    'manoel vitorino','marau','marco','mascote','mundo novo',
    'nazaré','olindina','oliveira dos brejinhos','ouricana',
    'palmas de monte alto','paripiranga','pedrao','pedro alexandre',
    'pilao arcado','planaltino','planalto','pocoes','presidente janio quadros',
    'quixabeira','randolandia','ribeirao do largo','rui barbosa',
    'santa barbara','santa luzia','santana','santanopolis',
    'sao miguel das matas','sao sebastiao do passe','saude',
    'simoes filho','tremedal','ubaraba','ubata','uirapuru',
    'umburanas','urandi','varzea nova','vera cruz',
    'vitoria da conquista','sao domingos','senhor do bonfim',
    'floresta azul','itaju do colonia','bonito','brotas',
    'cabaceiras do paraguacu','caetite','caldeirao grande',
    'camacan','camamu','canapolis','canarana','candido sales',
    'cansancao','capela do alto alegre','caravelas','carinhanha',
    'castro alves','catu','cerrolina','conde','contendas do sincora',
    'correntina','cristopolis','encruzilhada','esplanada',
    'filadelfia','firmiano alves','galeao','gameleira','gau',
    'guanambi','handomand','iaruba','ibirapua','ibipeba','ibitita',
    'igapo','ipecaeta','ipira','iramaia','itaberaba','itamaraju',
    'itape','itapebi','itapitanga','itaquara','itiruca','ituacu',
    'jaguaquara','jaguaripe','jandaira','jequie','jussara',
    'lajedo','lajedao','lajedinho','lapao','lencois',
    'licinio de almeida','livramento','luis eduardo magalhaes',
    'macajuba','macarani','machacalis','maetinga','malhada',
    'malhada de pedras','manoel vitorino','maracas','maragogipe',
    'marau','marco','mascote','mata de sao joao','medeiros neto',
    'mucuri','mundo novo','nazaré','olindina',
    'oliveira dos brejinhos','ouricana','palmas de monte alto',
    'paripiranga','pau brasil','pe de serra','pedrao',
    'pedro alexandre','pilao arcado','pirai do norte',
    'planaltino','planalto','pocoes','potiragua','prado',
    'presidente janio quadros','quixabeira','randolandia',
    'ribeira do pombal','ribeirao do largo','rui barbosa',
    'santa barbara','santa cruz cabralia','santa luzia',
    'santana','santanopolis','santo amaro','santo antonio de jesus',
    'sao felipe','sao francisco do conde','sao gabriel',
    'sao jose da vitoria','sao miguel das matas',
    'sao sebastiao do passe','sapeacu','saude','seabra','serrinha',
    'sento se','serra do salto','simoes filho','tanquinho',
    'tapiramuta','teixeira de freitas','teolandia','tremedal',
    'tucano','uaua','ubaraba','ubata','uirapuru','umburanas',
    'urandi','varzea do poco','varzea nova','varzedo',
    'vera cruz','vitoria da conquista','serapião','ponto novo',
    'paratinga','teixeirinha','rosangela','lira','luar',
}

google_fp = []
google_real = []
google_ambiguous = []

for r in google_records:
    nome = (r.get('nome') or r.get('name') or r.get('title') or '').strip()
    if not nome:
        continue

    nome_lower = nome.lower()

    # Check religious keywords first
    if has_religious_keyword(nome_lower):
        google_real.append({'nome': nome, 'fonte': 'google'})
        continue

    # Check non-religious patterns
    matched = None
    for label, pat in non_religious_patterns:
        if re.search(pat, nome_lower):
            matched = label
            break

    if matched:
        google_fp.append({'nome': nome, 'fonte': 'google', 'razao': matched,
                         'lat': r.get('lat'), 'lng': r.get('lng')})
        continue

    # Check if pure city name
    clean = nome_lower.strip()
    if clean in ba_city_names or clean.replace(' ba','').replace(' bahia','').replace('-ba','').replace(', bahia','').strip() in ba_city_names:
        google_fp.append({'nome': nome, 'fonte': 'google', 'razao': 'Nome de municipio BA',
                         'lat': r.get('lat'), 'lng': r.get('lng')})
        continue

    # Remaining
    google_ambiguous.append({'nome': nome, 'fonte': 'google', 'razao': 'Sem kw religiosa',
                             'lat': r.get('lat'), 'lng': r.get('lng')})

# Results
print(f"=== VARREDURA FOCADA: GOOGLE PLACES ({len(google_records)} registros) ===")
print()
print(f"Falsos positivos:            {len(google_fp):4d}")
print(f"Ambiguos (sem kw religiosa): {len(google_ambiguous):4d}")
print(f"Reais (com kw religiosa):    {len(google_real):4d}")
print()
print(f"Fontes nao-Google (nao escaneadas - curadas): {len(non_google)}")
print(f"  CEAO, SEFAZ, OSM = registros academicos/oficiais")
print()

print(f"=== FALSOS POSITIVOS GOOGLE ({len(google_fp)}) ===")
razao_counts = Counter(s['razao'] for s in google_fp)
for razao, count in razao_counts.most_common():
    print(f"  {razao}: {count}")
print()
for i, s in enumerate(sorted(google_fp, key=lambda x: (x['razao'], x['nome'])), 1):
    print(f"  {i:3d}. {s['nome'][:70]:70s} | {s['razao']}")

print(f"\n=== AMBIGUOS GOOGLE ({len(google_ambiguous)}) ===")
for i, s in enumerate(sorted(google_ambiguous, key=lambda x: x['nome']), 1):
    print(f"  {i:3d}. {s['nome'][:70]:70s}")

# Save
output = {
    'google_false_positives': google_fp,
    'google_ambiguous': google_ambiguous,
    'google_real_count': len(google_real),
    'non_google_total': len(non_google),
    'summary': {
        'google_total': len(google_records),
        'google_fp': len(google_fp),
        'google_ambiguous': len(google_ambiguous),
        'google_real': len(google_real),
        'non_google': len(non_google),
        'fp_rate_google': f"{len(google_fp)/max(len(google_records),1)*100:.1f}%",
        'total_dataset': len(records),
        'total_fp_all_sources': len(google_fp),
    }
}
with open('data/falsos_positivos_suspeitos.json', 'w') as f:
    json.dump(output, f, ensure_ascii=False, indent=2)
print(f"\nSalvo: data/falsos_positivos_suspeitos.json")